const AWS_ACCESS_KEY_ID = "AKIAIOSFODNN7EXAMPLE";
const AWS_SECRET_ACCESS_KEY = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"; //Examples of credentials

export { AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY };